//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class FunctionKeys : Neo.ApplicationFramework.Tools.FunctionKey.FunctionKeyManager
	{
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F1;
		
		private System.ComponentModel.IContainer components;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F2;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F3;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F4;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F5;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F6;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F7;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F8;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F9;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F10;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F11;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F12;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F13;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F14;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F15;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F16;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F17;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F18;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F19;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F20;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F21;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F22;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F23;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_F24;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_Screen1;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F1;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F2;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F3;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F4;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F5;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F6;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F7;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F8;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F9;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F10;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F11;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F12;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F13;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F14;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F15;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F16;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F17;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F18;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F19;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F20;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F21;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F22;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F23;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen1_F24;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_Screen2;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F1;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F2;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F3;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F4;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F5;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F6;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F7;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F8;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F9;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F10;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F11;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F12;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F13;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F14;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F15;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F16;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F17;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F18;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F19;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F20;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F21;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F22;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F23;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen2_F24;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext m_Screen3;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F1;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F2;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F3;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F4;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F5;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F6;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F7;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F8;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F9;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F10;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F11;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F12;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F13;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F14;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F15;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F16;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F17;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F18;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F19;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F20;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F21;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F22;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F23;
		
		private Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey m_Screen3_F24;
		
		public FunctionKeys()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F1
		{
			get
			{
				return this.m_F1;
			}
			set
			{
				this.m_F1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F2
		{
			get
			{
				return this.m_F2;
			}
			set
			{
				this.m_F2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F3
		{
			get
			{
				return this.m_F3;
			}
			set
			{
				this.m_F3 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F4
		{
			get
			{
				return this.m_F4;
			}
			set
			{
				this.m_F4 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F5
		{
			get
			{
				return this.m_F5;
			}
			set
			{
				this.m_F5 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F6
		{
			get
			{
				return this.m_F6;
			}
			set
			{
				this.m_F6 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F7
		{
			get
			{
				return this.m_F7;
			}
			set
			{
				this.m_F7 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F8
		{
			get
			{
				return this.m_F8;
			}
			set
			{
				this.m_F8 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F9
		{
			get
			{
				return this.m_F9;
			}
			set
			{
				this.m_F9 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F10
		{
			get
			{
				return this.m_F10;
			}
			set
			{
				this.m_F10 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F11
		{
			get
			{
				return this.m_F11;
			}
			set
			{
				this.m_F11 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F12
		{
			get
			{
				return this.m_F12;
			}
			set
			{
				this.m_F12 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F13
		{
			get
			{
				return this.m_F13;
			}
			set
			{
				this.m_F13 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F14
		{
			get
			{
				return this.m_F14;
			}
			set
			{
				this.m_F14 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F15
		{
			get
			{
				return this.m_F15;
			}
			set
			{
				this.m_F15 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F16
		{
			get
			{
				return this.m_F16;
			}
			set
			{
				this.m_F16 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F17
		{
			get
			{
				return this.m_F17;
			}
			set
			{
				this.m_F17 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F18
		{
			get
			{
				return this.m_F18;
			}
			set
			{
				this.m_F18 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F19
		{
			get
			{
				return this.m_F19;
			}
			set
			{
				this.m_F19 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F20
		{
			get
			{
				return this.m_F20;
			}
			set
			{
				this.m_F20 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F21
		{
			get
			{
				return this.m_F21;
			}
			set
			{
				this.m_F21 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F22
		{
			get
			{
				return this.m_F22;
			}
			set
			{
				this.m_F22 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F23
		{
			get
			{
				return this.m_F23;
			}
			set
			{
				this.m_F23 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey F24
		{
			get
			{
				return this.m_F24;
			}
			set
			{
				this.m_F24 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext Screen1
		{
			get
			{
				return this.m_Screen1;
			}
			set
			{
				this.m_Screen1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F1
		{
			get
			{
				return this.m_Screen1_F1;
			}
			set
			{
				this.m_Screen1_F1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F2
		{
			get
			{
				return this.m_Screen1_F2;
			}
			set
			{
				this.m_Screen1_F2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F3
		{
			get
			{
				return this.m_Screen1_F3;
			}
			set
			{
				this.m_Screen1_F3 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F4
		{
			get
			{
				return this.m_Screen1_F4;
			}
			set
			{
				this.m_Screen1_F4 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F5
		{
			get
			{
				return this.m_Screen1_F5;
			}
			set
			{
				this.m_Screen1_F5 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F6
		{
			get
			{
				return this.m_Screen1_F6;
			}
			set
			{
				this.m_Screen1_F6 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F7
		{
			get
			{
				return this.m_Screen1_F7;
			}
			set
			{
				this.m_Screen1_F7 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F8
		{
			get
			{
				return this.m_Screen1_F8;
			}
			set
			{
				this.m_Screen1_F8 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F9
		{
			get
			{
				return this.m_Screen1_F9;
			}
			set
			{
				this.m_Screen1_F9 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F10
		{
			get
			{
				return this.m_Screen1_F10;
			}
			set
			{
				this.m_Screen1_F10 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F11
		{
			get
			{
				return this.m_Screen1_F11;
			}
			set
			{
				this.m_Screen1_F11 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F12
		{
			get
			{
				return this.m_Screen1_F12;
			}
			set
			{
				this.m_Screen1_F12 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F13
		{
			get
			{
				return this.m_Screen1_F13;
			}
			set
			{
				this.m_Screen1_F13 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F14
		{
			get
			{
				return this.m_Screen1_F14;
			}
			set
			{
				this.m_Screen1_F14 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F15
		{
			get
			{
				return this.m_Screen1_F15;
			}
			set
			{
				this.m_Screen1_F15 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F16
		{
			get
			{
				return this.m_Screen1_F16;
			}
			set
			{
				this.m_Screen1_F16 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F17
		{
			get
			{
				return this.m_Screen1_F17;
			}
			set
			{
				this.m_Screen1_F17 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F18
		{
			get
			{
				return this.m_Screen1_F18;
			}
			set
			{
				this.m_Screen1_F18 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F19
		{
			get
			{
				return this.m_Screen1_F19;
			}
			set
			{
				this.m_Screen1_F19 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F20
		{
			get
			{
				return this.m_Screen1_F20;
			}
			set
			{
				this.m_Screen1_F20 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F21
		{
			get
			{
				return this.m_Screen1_F21;
			}
			set
			{
				this.m_Screen1_F21 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F22
		{
			get
			{
				return this.m_Screen1_F22;
			}
			set
			{
				this.m_Screen1_F22 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F23
		{
			get
			{
				return this.m_Screen1_F23;
			}
			set
			{
				this.m_Screen1_F23 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen1_F24
		{
			get
			{
				return this.m_Screen1_F24;
			}
			set
			{
				this.m_Screen1_F24 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext Screen2
		{
			get
			{
				return this.m_Screen2;
			}
			set
			{
				this.m_Screen2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F1
		{
			get
			{
				return this.m_Screen2_F1;
			}
			set
			{
				this.m_Screen2_F1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F2
		{
			get
			{
				return this.m_Screen2_F2;
			}
			set
			{
				this.m_Screen2_F2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F3
		{
			get
			{
				return this.m_Screen2_F3;
			}
			set
			{
				this.m_Screen2_F3 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F4
		{
			get
			{
				return this.m_Screen2_F4;
			}
			set
			{
				this.m_Screen2_F4 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F5
		{
			get
			{
				return this.m_Screen2_F5;
			}
			set
			{
				this.m_Screen2_F5 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F6
		{
			get
			{
				return this.m_Screen2_F6;
			}
			set
			{
				this.m_Screen2_F6 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F7
		{
			get
			{
				return this.m_Screen2_F7;
			}
			set
			{
				this.m_Screen2_F7 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F8
		{
			get
			{
				return this.m_Screen2_F8;
			}
			set
			{
				this.m_Screen2_F8 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F9
		{
			get
			{
				return this.m_Screen2_F9;
			}
			set
			{
				this.m_Screen2_F9 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F10
		{
			get
			{
				return this.m_Screen2_F10;
			}
			set
			{
				this.m_Screen2_F10 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F11
		{
			get
			{
				return this.m_Screen2_F11;
			}
			set
			{
				this.m_Screen2_F11 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F12
		{
			get
			{
				return this.m_Screen2_F12;
			}
			set
			{
				this.m_Screen2_F12 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F13
		{
			get
			{
				return this.m_Screen2_F13;
			}
			set
			{
				this.m_Screen2_F13 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F14
		{
			get
			{
				return this.m_Screen2_F14;
			}
			set
			{
				this.m_Screen2_F14 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F15
		{
			get
			{
				return this.m_Screen2_F15;
			}
			set
			{
				this.m_Screen2_F15 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F16
		{
			get
			{
				return this.m_Screen2_F16;
			}
			set
			{
				this.m_Screen2_F16 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F17
		{
			get
			{
				return this.m_Screen2_F17;
			}
			set
			{
				this.m_Screen2_F17 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F18
		{
			get
			{
				return this.m_Screen2_F18;
			}
			set
			{
				this.m_Screen2_F18 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F19
		{
			get
			{
				return this.m_Screen2_F19;
			}
			set
			{
				this.m_Screen2_F19 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F20
		{
			get
			{
				return this.m_Screen2_F20;
			}
			set
			{
				this.m_Screen2_F20 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F21
		{
			get
			{
				return this.m_Screen2_F21;
			}
			set
			{
				this.m_Screen2_F21 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F22
		{
			get
			{
				return this.m_Screen2_F22;
			}
			set
			{
				this.m_Screen2_F22 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F23
		{
			get
			{
				return this.m_Screen2_F23;
			}
			set
			{
				this.m_Screen2_F23 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen2_F24
		{
			get
			{
				return this.m_Screen2_F24;
			}
			set
			{
				this.m_Screen2_F24 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext Screen3
		{
			get
			{
				return this.m_Screen3;
			}
			set
			{
				this.m_Screen3 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F1
		{
			get
			{
				return this.m_Screen3_F1;
			}
			set
			{
				this.m_Screen3_F1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F2
		{
			get
			{
				return this.m_Screen3_F2;
			}
			set
			{
				this.m_Screen3_F2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F3
		{
			get
			{
				return this.m_Screen3_F3;
			}
			set
			{
				this.m_Screen3_F3 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F4
		{
			get
			{
				return this.m_Screen3_F4;
			}
			set
			{
				this.m_Screen3_F4 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F5
		{
			get
			{
				return this.m_Screen3_F5;
			}
			set
			{
				this.m_Screen3_F5 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F6
		{
			get
			{
				return this.m_Screen3_F6;
			}
			set
			{
				this.m_Screen3_F6 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F7
		{
			get
			{
				return this.m_Screen3_F7;
			}
			set
			{
				this.m_Screen3_F7 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F8
		{
			get
			{
				return this.m_Screen3_F8;
			}
			set
			{
				this.m_Screen3_F8 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F9
		{
			get
			{
				return this.m_Screen3_F9;
			}
			set
			{
				this.m_Screen3_F9 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F10
		{
			get
			{
				return this.m_Screen3_F10;
			}
			set
			{
				this.m_Screen3_F10 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F11
		{
			get
			{
				return this.m_Screen3_F11;
			}
			set
			{
				this.m_Screen3_F11 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F12
		{
			get
			{
				return this.m_Screen3_F12;
			}
			set
			{
				this.m_Screen3_F12 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F13
		{
			get
			{
				return this.m_Screen3_F13;
			}
			set
			{
				this.m_Screen3_F13 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F14
		{
			get
			{
				return this.m_Screen3_F14;
			}
			set
			{
				this.m_Screen3_F14 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F15
		{
			get
			{
				return this.m_Screen3_F15;
			}
			set
			{
				this.m_Screen3_F15 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F16
		{
			get
			{
				return this.m_Screen3_F16;
			}
			set
			{
				this.m_Screen3_F16 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F17
		{
			get
			{
				return this.m_Screen3_F17;
			}
			set
			{
				this.m_Screen3_F17 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F18
		{
			get
			{
				return this.m_Screen3_F18;
			}
			set
			{
				this.m_Screen3_F18 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F19
		{
			get
			{
				return this.m_Screen3_F19;
			}
			set
			{
				this.m_Screen3_F19 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F20
		{
			get
			{
				return this.m_Screen3_F20;
			}
			set
			{
				this.m_Screen3_F20 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F21
		{
			get
			{
				return this.m_Screen3_F21;
			}
			set
			{
				this.m_Screen3_F21 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F22
		{
			get
			{
				return this.m_Screen3_F22;
			}
			set
			{
				this.m_Screen3_F22 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F23
		{
			get
			{
				return this.m_Screen3_F23;
			}
			set
			{
				this.m_Screen3_F23 = value;
			}
		}
		
		public Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey Screen3_F24
		{
			get
			{
				return this.m_Screen3_F24;
			}
			set
			{
				this.m_Screen3_F24 = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
			this.components.Dispose();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.components = new System.ComponentModel.Container();
			this.F1 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F2 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F3 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F4 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F5 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F6 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F7 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F8 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F9 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F10 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F11 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F12 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F13 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F14 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F15 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F16 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F17 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F18 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F19 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F20 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F21 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F22 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F23 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.F24 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.Screen1_F1 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F2 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F3 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F4 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F5 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F6 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F7 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F8 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F9 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F10 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F11 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F12 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F13 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F14 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F15 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F16 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F17 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F18 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F19 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F20 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F21 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F22 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F23 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen1_F24 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.Screen2_F1 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F2 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F3 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F4 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F5 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F6 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F7 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F8 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F9 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F10 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F11 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F12 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F13 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F14 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F15 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F16 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F17 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F18 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F19 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F20 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F21 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F22 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F23 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen2_F24 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKeyContext();
			this.Screen3_F1 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F2 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F3 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F4 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F5 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F6 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F7 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F8 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F9 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F10 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F11 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F12 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F13 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F14 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F15 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F16 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F17 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F18 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F19 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F20 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F21 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F22 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F23 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
			this.Screen3_F24 = new Neo.ApplicationFramework.Controls.FunctionKey.FunctionKey(this.components);
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F7)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F8)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F9)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F10)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F11)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F12)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F13)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F14)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F15)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F16)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F17)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F18)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F19)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F20)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F21)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F22)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F23)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.F24)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F7)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F8)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F9)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F10)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F11)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F12)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F13)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F14)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F15)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F16)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F17)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F18)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F19)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F20)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F21)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F22)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F23)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F24)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F7)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F8)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F9)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F10)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F11)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F12)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F13)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F14)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F15)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F16)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F17)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F18)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F19)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F20)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F21)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F22)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F23)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F24)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F7)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F8)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F9)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F10)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F11)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F12)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F13)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F14)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F15)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F16)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F17)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F18)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F19)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F20)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F21)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F22)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F23)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F24)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.F1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F8)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F9)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F10)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F11)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F12)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F13)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F14)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F15)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F16)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F17)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F18)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F19)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F20)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F21)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F22)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F23)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.F24)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F8)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F9)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F10)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F11)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F12)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F13)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F14)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F15)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F16)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F17)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F18)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F19)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F20)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F21)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F22)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F23)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen1_F24)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F8)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F9)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F10)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F11)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F12)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F13)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F14)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F15)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F16)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F17)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F18)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F19)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F20)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F21)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F22)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F23)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen2_F24)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F8)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F9)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F10)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F11)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F12)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F13)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F14)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F15)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F16)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F17)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F18)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F19)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F20)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F21)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F22)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F23)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.Screen3_F24)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.F1.KeyCode = System.Windows.Forms.Keys.F1;
			this.F1.Name = "F1";
			this.F2.KeyCode = System.Windows.Forms.Keys.F2;
			this.F2.Name = "F2";
			this.F3.KeyCode = System.Windows.Forms.Keys.F3;
			this.F3.Name = "F3";
			this.F4.KeyCode = System.Windows.Forms.Keys.F4;
			this.F4.Name = "F4";
			this.F5.KeyCode = System.Windows.Forms.Keys.F5;
			this.F5.Name = "F5";
			this.F6.KeyCode = System.Windows.Forms.Keys.F6;
			this.F6.Name = "F6";
			this.F7.KeyCode = System.Windows.Forms.Keys.F7;
			this.F7.Name = "F7";
			this.F8.KeyCode = System.Windows.Forms.Keys.F8;
			this.F8.Name = "F8";
			this.F9.KeyCode = System.Windows.Forms.Keys.F9;
			this.F9.Name = "F9";
			this.F10.KeyCode = System.Windows.Forms.Keys.F10;
			this.F10.Name = "F10";
			this.F11.KeyCode = System.Windows.Forms.Keys.F11;
			this.F11.Name = "F11";
			this.F12.KeyCode = System.Windows.Forms.Keys.F12;
			this.F12.Name = "F12";
			this.F13.KeyCode = System.Windows.Forms.Keys.F13;
			this.F13.Name = "F13";
			this.F14.KeyCode = System.Windows.Forms.Keys.F14;
			this.F14.Name = "F14";
			this.F15.KeyCode = System.Windows.Forms.Keys.F15;
			this.F15.Name = "F15";
			this.F16.KeyCode = System.Windows.Forms.Keys.F16;
			this.F16.Name = "F16";
			this.F17.KeyCode = System.Windows.Forms.Keys.F17;
			this.F17.Name = "F17";
			this.F18.KeyCode = System.Windows.Forms.Keys.F18;
			this.F18.Name = "F18";
			this.F19.KeyCode = System.Windows.Forms.Keys.F19;
			this.F19.Name = "F19";
			this.F20.KeyCode = System.Windows.Forms.Keys.F20;
			this.F20.Name = "F20";
			this.F21.KeyCode = System.Windows.Forms.Keys.F21;
			this.F21.Name = "F21";
			this.F22.KeyCode = System.Windows.Forms.Keys.F22;
			this.F22.Name = "F22";
			this.F23.KeyCode = System.Windows.Forms.Keys.F23;
			this.F23.Name = "F23";
			this.F24.KeyCode = System.Windows.Forms.Keys.F24;
			this.F24.Name = "F24";
			this.GlobalFunctionKeys.Add(this.F1);
			this.GlobalFunctionKeys.Add(this.F2);
			this.GlobalFunctionKeys.Add(this.F3);
			this.GlobalFunctionKeys.Add(this.F4);
			this.GlobalFunctionKeys.Add(this.F5);
			this.GlobalFunctionKeys.Add(this.F6);
			this.GlobalFunctionKeys.Add(this.F7);
			this.GlobalFunctionKeys.Add(this.F8);
			this.GlobalFunctionKeys.Add(this.F9);
			this.GlobalFunctionKeys.Add(this.F10);
			this.GlobalFunctionKeys.Add(this.F11);
			this.GlobalFunctionKeys.Add(this.F12);
			this.GlobalFunctionKeys.Add(this.F13);
			this.GlobalFunctionKeys.Add(this.F14);
			this.GlobalFunctionKeys.Add(this.F15);
			this.GlobalFunctionKeys.Add(this.F16);
			this.GlobalFunctionKeys.Add(this.F17);
			this.GlobalFunctionKeys.Add(this.F18);
			this.GlobalFunctionKeys.Add(this.F19);
			this.GlobalFunctionKeys.Add(this.F20);
			this.GlobalFunctionKeys.Add(this.F21);
			this.GlobalFunctionKeys.Add(this.F22);
			this.GlobalFunctionKeys.Add(this.F23);
			this.GlobalFunctionKeys.Add(this.F24);
			this.Screen1_F1.KeyCode = System.Windows.Forms.Keys.F1;
			this.Screen1_F1.Name = "Screen1_F1";
			this.Screen1_F2.KeyCode = System.Windows.Forms.Keys.F2;
			this.Screen1_F2.Name = "Screen1_F2";
			this.Screen1_F3.KeyCode = System.Windows.Forms.Keys.F3;
			this.Screen1_F3.Name = "Screen1_F3";
			this.Screen1_F4.KeyCode = System.Windows.Forms.Keys.F4;
			this.Screen1_F4.Name = "Screen1_F4";
			this.Screen1_F5.KeyCode = System.Windows.Forms.Keys.F5;
			this.Screen1_F5.Name = "Screen1_F5";
			this.Screen1_F6.KeyCode = System.Windows.Forms.Keys.F6;
			this.Screen1_F6.Name = "Screen1_F6";
			this.Screen1_F7.KeyCode = System.Windows.Forms.Keys.F7;
			this.Screen1_F7.Name = "Screen1_F7";
			this.Screen1_F8.KeyCode = System.Windows.Forms.Keys.F8;
			this.Screen1_F8.Name = "Screen1_F8";
			this.Screen1_F9.KeyCode = System.Windows.Forms.Keys.F9;
			this.Screen1_F9.Name = "Screen1_F9";
			this.Screen1_F10.KeyCode = System.Windows.Forms.Keys.F10;
			this.Screen1_F10.Name = "Screen1_F10";
			this.Screen1_F11.KeyCode = System.Windows.Forms.Keys.F11;
			this.Screen1_F11.Name = "Screen1_F11";
			this.Screen1_F12.KeyCode = System.Windows.Forms.Keys.F12;
			this.Screen1_F12.Name = "Screen1_F12";
			this.Screen1_F13.KeyCode = System.Windows.Forms.Keys.F13;
			this.Screen1_F13.Name = "Screen1_F13";
			this.Screen1_F14.KeyCode = System.Windows.Forms.Keys.F14;
			this.Screen1_F14.Name = "Screen1_F14";
			this.Screen1_F15.KeyCode = System.Windows.Forms.Keys.F15;
			this.Screen1_F15.Name = "Screen1_F15";
			this.Screen1_F16.KeyCode = System.Windows.Forms.Keys.F16;
			this.Screen1_F16.Name = "Screen1_F16";
			this.Screen1_F17.KeyCode = System.Windows.Forms.Keys.F17;
			this.Screen1_F17.Name = "Screen1_F17";
			this.Screen1_F18.KeyCode = System.Windows.Forms.Keys.F18;
			this.Screen1_F18.Name = "Screen1_F18";
			this.Screen1_F19.KeyCode = System.Windows.Forms.Keys.F19;
			this.Screen1_F19.Name = "Screen1_F19";
			this.Screen1_F20.KeyCode = System.Windows.Forms.Keys.F20;
			this.Screen1_F20.Name = "Screen1_F20";
			this.Screen1_F21.KeyCode = System.Windows.Forms.Keys.F21;
			this.Screen1_F21.Name = "Screen1_F21";
			this.Screen1_F22.KeyCode = System.Windows.Forms.Keys.F22;
			this.Screen1_F22.Name = "Screen1_F22";
			this.Screen1_F23.KeyCode = System.Windows.Forms.Keys.F23;
			this.Screen1_F23.Name = "Screen1_F23";
			this.Screen1_F24.KeyCode = System.Windows.Forms.Keys.F24;
			this.Screen1_F24.Name = "Screen1_F24";
			this.Screen1.FunctionKeys.Add(this.Screen1_F1);
			this.Screen1.FunctionKeys.Add(this.Screen1_F2);
			this.Screen1.FunctionKeys.Add(this.Screen1_F3);
			this.Screen1.FunctionKeys.Add(this.Screen1_F4);
			this.Screen1.FunctionKeys.Add(this.Screen1_F5);
			this.Screen1.FunctionKeys.Add(this.Screen1_F6);
			this.Screen1.FunctionKeys.Add(this.Screen1_F7);
			this.Screen1.FunctionKeys.Add(this.Screen1_F8);
			this.Screen1.FunctionKeys.Add(this.Screen1_F9);
			this.Screen1.FunctionKeys.Add(this.Screen1_F10);
			this.Screen1.FunctionKeys.Add(this.Screen1_F11);
			this.Screen1.FunctionKeys.Add(this.Screen1_F12);
			this.Screen1.FunctionKeys.Add(this.Screen1_F13);
			this.Screen1.FunctionKeys.Add(this.Screen1_F14);
			this.Screen1.FunctionKeys.Add(this.Screen1_F15);
			this.Screen1.FunctionKeys.Add(this.Screen1_F16);
			this.Screen1.FunctionKeys.Add(this.Screen1_F17);
			this.Screen1.FunctionKeys.Add(this.Screen1_F18);
			this.Screen1.FunctionKeys.Add(this.Screen1_F19);
			this.Screen1.FunctionKeys.Add(this.Screen1_F20);
			this.Screen1.FunctionKeys.Add(this.Screen1_F21);
			this.Screen1.FunctionKeys.Add(this.Screen1_F22);
			this.Screen1.FunctionKeys.Add(this.Screen1_F23);
			this.Screen1.FunctionKeys.Add(this.Screen1_F24);
			this.Screen1.Name = "Screen1";
			this.Screen1.ScreenName = "Screen1";
			this.Screen2_F1.KeyCode = System.Windows.Forms.Keys.F1;
			this.Screen2_F1.Name = "Screen2_F1";
			this.Screen2_F2.KeyCode = System.Windows.Forms.Keys.F2;
			this.Screen2_F2.Name = "Screen2_F2";
			this.Screen2_F3.KeyCode = System.Windows.Forms.Keys.F3;
			this.Screen2_F3.Name = "Screen2_F3";
			this.Screen2_F4.KeyCode = System.Windows.Forms.Keys.F4;
			this.Screen2_F4.Name = "Screen2_F4";
			this.Screen2_F5.KeyCode = System.Windows.Forms.Keys.F5;
			this.Screen2_F5.Name = "Screen2_F5";
			this.Screen2_F6.KeyCode = System.Windows.Forms.Keys.F6;
			this.Screen2_F6.Name = "Screen2_F6";
			this.Screen2_F7.KeyCode = System.Windows.Forms.Keys.F7;
			this.Screen2_F7.Name = "Screen2_F7";
			this.Screen2_F8.KeyCode = System.Windows.Forms.Keys.F8;
			this.Screen2_F8.Name = "Screen2_F8";
			this.Screen2_F9.KeyCode = System.Windows.Forms.Keys.F9;
			this.Screen2_F9.Name = "Screen2_F9";
			this.Screen2_F10.KeyCode = System.Windows.Forms.Keys.F10;
			this.Screen2_F10.Name = "Screen2_F10";
			this.Screen2_F11.KeyCode = System.Windows.Forms.Keys.F11;
			this.Screen2_F11.Name = "Screen2_F11";
			this.Screen2_F12.KeyCode = System.Windows.Forms.Keys.F12;
			this.Screen2_F12.Name = "Screen2_F12";
			this.Screen2_F13.KeyCode = System.Windows.Forms.Keys.F13;
			this.Screen2_F13.Name = "Screen2_F13";
			this.Screen2_F14.KeyCode = System.Windows.Forms.Keys.F14;
			this.Screen2_F14.Name = "Screen2_F14";
			this.Screen2_F15.KeyCode = System.Windows.Forms.Keys.F15;
			this.Screen2_F15.Name = "Screen2_F15";
			this.Screen2_F16.KeyCode = System.Windows.Forms.Keys.F16;
			this.Screen2_F16.Name = "Screen2_F16";
			this.Screen2_F17.KeyCode = System.Windows.Forms.Keys.F17;
			this.Screen2_F17.Name = "Screen2_F17";
			this.Screen2_F18.KeyCode = System.Windows.Forms.Keys.F18;
			this.Screen2_F18.Name = "Screen2_F18";
			this.Screen2_F19.KeyCode = System.Windows.Forms.Keys.F19;
			this.Screen2_F19.Name = "Screen2_F19";
			this.Screen2_F20.KeyCode = System.Windows.Forms.Keys.F20;
			this.Screen2_F20.Name = "Screen2_F20";
			this.Screen2_F21.KeyCode = System.Windows.Forms.Keys.F21;
			this.Screen2_F21.Name = "Screen2_F21";
			this.Screen2_F22.KeyCode = System.Windows.Forms.Keys.F22;
			this.Screen2_F22.Name = "Screen2_F22";
			this.Screen2_F23.KeyCode = System.Windows.Forms.Keys.F23;
			this.Screen2_F23.Name = "Screen2_F23";
			this.Screen2_F24.KeyCode = System.Windows.Forms.Keys.F24;
			this.Screen2_F24.Name = "Screen2_F24";
			this.Screen2.FunctionKeys.Add(this.Screen2_F1);
			this.Screen2.FunctionKeys.Add(this.Screen2_F2);
			this.Screen2.FunctionKeys.Add(this.Screen2_F3);
			this.Screen2.FunctionKeys.Add(this.Screen2_F4);
			this.Screen2.FunctionKeys.Add(this.Screen2_F5);
			this.Screen2.FunctionKeys.Add(this.Screen2_F6);
			this.Screen2.FunctionKeys.Add(this.Screen2_F7);
			this.Screen2.FunctionKeys.Add(this.Screen2_F8);
			this.Screen2.FunctionKeys.Add(this.Screen2_F9);
			this.Screen2.FunctionKeys.Add(this.Screen2_F10);
			this.Screen2.FunctionKeys.Add(this.Screen2_F11);
			this.Screen2.FunctionKeys.Add(this.Screen2_F12);
			this.Screen2.FunctionKeys.Add(this.Screen2_F13);
			this.Screen2.FunctionKeys.Add(this.Screen2_F14);
			this.Screen2.FunctionKeys.Add(this.Screen2_F15);
			this.Screen2.FunctionKeys.Add(this.Screen2_F16);
			this.Screen2.FunctionKeys.Add(this.Screen2_F17);
			this.Screen2.FunctionKeys.Add(this.Screen2_F18);
			this.Screen2.FunctionKeys.Add(this.Screen2_F19);
			this.Screen2.FunctionKeys.Add(this.Screen2_F20);
			this.Screen2.FunctionKeys.Add(this.Screen2_F21);
			this.Screen2.FunctionKeys.Add(this.Screen2_F22);
			this.Screen2.FunctionKeys.Add(this.Screen2_F23);
			this.Screen2.FunctionKeys.Add(this.Screen2_F24);
			this.Screen2.Name = "Screen2";
			this.Screen2.ScreenName = "Screen2";
			this.Screen3_F1.KeyCode = System.Windows.Forms.Keys.F1;
			this.Screen3_F1.Name = "Screen3_F1";
			this.Screen3_F2.KeyCode = System.Windows.Forms.Keys.F2;
			this.Screen3_F2.Name = "Screen3_F2";
			this.Screen3_F3.KeyCode = System.Windows.Forms.Keys.F3;
			this.Screen3_F3.Name = "Screen3_F3";
			this.Screen3_F4.KeyCode = System.Windows.Forms.Keys.F4;
			this.Screen3_F4.Name = "Screen3_F4";
			this.Screen3_F5.KeyCode = System.Windows.Forms.Keys.F5;
			this.Screen3_F5.Name = "Screen3_F5";
			this.Screen3_F6.KeyCode = System.Windows.Forms.Keys.F6;
			this.Screen3_F6.Name = "Screen3_F6";
			this.Screen3_F7.KeyCode = System.Windows.Forms.Keys.F7;
			this.Screen3_F7.Name = "Screen3_F7";
			this.Screen3_F8.KeyCode = System.Windows.Forms.Keys.F8;
			this.Screen3_F8.Name = "Screen3_F8";
			this.Screen3_F9.KeyCode = System.Windows.Forms.Keys.F9;
			this.Screen3_F9.Name = "Screen3_F9";
			this.Screen3_F10.KeyCode = System.Windows.Forms.Keys.F10;
			this.Screen3_F10.Name = "Screen3_F10";
			this.Screen3_F11.KeyCode = System.Windows.Forms.Keys.F11;
			this.Screen3_F11.Name = "Screen3_F11";
			this.Screen3_F12.KeyCode = System.Windows.Forms.Keys.F12;
			this.Screen3_F12.Name = "Screen3_F12";
			this.Screen3_F13.KeyCode = System.Windows.Forms.Keys.F13;
			this.Screen3_F13.Name = "Screen3_F13";
			this.Screen3_F14.KeyCode = System.Windows.Forms.Keys.F14;
			this.Screen3_F14.Name = "Screen3_F14";
			this.Screen3_F15.KeyCode = System.Windows.Forms.Keys.F15;
			this.Screen3_F15.Name = "Screen3_F15";
			this.Screen3_F16.KeyCode = System.Windows.Forms.Keys.F16;
			this.Screen3_F16.Name = "Screen3_F16";
			this.Screen3_F17.KeyCode = System.Windows.Forms.Keys.F17;
			this.Screen3_F17.Name = "Screen3_F17";
			this.Screen3_F18.KeyCode = System.Windows.Forms.Keys.F18;
			this.Screen3_F18.Name = "Screen3_F18";
			this.Screen3_F19.KeyCode = System.Windows.Forms.Keys.F19;
			this.Screen3_F19.Name = "Screen3_F19";
			this.Screen3_F20.KeyCode = System.Windows.Forms.Keys.F20;
			this.Screen3_F20.Name = "Screen3_F20";
			this.Screen3_F21.KeyCode = System.Windows.Forms.Keys.F21;
			this.Screen3_F21.Name = "Screen3_F21";
			this.Screen3_F22.KeyCode = System.Windows.Forms.Keys.F22;
			this.Screen3_F22.Name = "Screen3_F22";
			this.Screen3_F23.KeyCode = System.Windows.Forms.Keys.F23;
			this.Screen3_F23.Name = "Screen3_F23";
			this.Screen3_F24.KeyCode = System.Windows.Forms.Keys.F24;
			this.Screen3_F24.Name = "Screen3_F24";
			this.Screen3.FunctionKeys.Add(this.Screen3_F1);
			this.Screen3.FunctionKeys.Add(this.Screen3_F2);
			this.Screen3.FunctionKeys.Add(this.Screen3_F3);
			this.Screen3.FunctionKeys.Add(this.Screen3_F4);
			this.Screen3.FunctionKeys.Add(this.Screen3_F5);
			this.Screen3.FunctionKeys.Add(this.Screen3_F6);
			this.Screen3.FunctionKeys.Add(this.Screen3_F7);
			this.Screen3.FunctionKeys.Add(this.Screen3_F8);
			this.Screen3.FunctionKeys.Add(this.Screen3_F9);
			this.Screen3.FunctionKeys.Add(this.Screen3_F10);
			this.Screen3.FunctionKeys.Add(this.Screen3_F11);
			this.Screen3.FunctionKeys.Add(this.Screen3_F12);
			this.Screen3.FunctionKeys.Add(this.Screen3_F13);
			this.Screen3.FunctionKeys.Add(this.Screen3_F14);
			this.Screen3.FunctionKeys.Add(this.Screen3_F15);
			this.Screen3.FunctionKeys.Add(this.Screen3_F16);
			this.Screen3.FunctionKeys.Add(this.Screen3_F17);
			this.Screen3.FunctionKeys.Add(this.Screen3_F18);
			this.Screen3.FunctionKeys.Add(this.Screen3_F19);
			this.Screen3.FunctionKeys.Add(this.Screen3_F20);
			this.Screen3.FunctionKeys.Add(this.Screen3_F21);
			this.Screen3.FunctionKeys.Add(this.Screen3_F22);
			this.Screen3.FunctionKeys.Add(this.Screen3_F23);
			this.Screen3.FunctionKeys.Add(this.Screen3_F24);
			this.Screen3.Name = "Screen3";
			this.Screen3.ScreenName = "Screen3";
			this.LocalFunctionKeys.Add(this.Screen1);
			this.LocalFunctionKeys.Add(this.Screen2);
			this.LocalFunctionKeys.Add(this.Screen3);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(FunctionKeys));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
