//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	public partial class TextLibrary : Neo.ApplicationFramework.Common.MessageLibrary.MessageLibrary
	{
		
		private Neo.ApplicationFramework.Common.MessageLibrary.MessageGroup m_Group1;
		
		private Neo.ApplicationFramework.Common.MessageLibrary.MessageItem m_Group1_MessageItem0;
		
		public TextLibrary()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Common.MessageLibrary.MessageGroup Group1
		{
			get
			{
				return this.m_Group1;
			}
			set
			{
				this.m_Group1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Common.MessageLibrary.MessageItem Group1_MessageItem0
		{
			get
			{
				return this.m_Group1_MessageItem0;
			}
			set
			{
				this.m_Group1_MessageItem0 = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public override void ConnectDataBindings()
		{
			base.ConnectDataBindings();
		}
		
		private void InitializeObjectCreations()
		{
			this.Group1 = new Neo.ApplicationFramework.Common.MessageLibrary.MessageGroup();
			this.Group1_MessageItem0 = new Neo.ApplicationFramework.Common.MessageLibrary.MessageItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.Group1_MessageItem0)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.Group1_MessageItem0)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.Group1_MessageItem0.DisplayName = "MessageItem0";
			this.Group1_MessageItem0.EndValue = 0;
			this.Group1_MessageItem0.GroupName = "Group1";
			this.Group1_MessageItem0.Name = "Group1_MessageItem0";
			this.Group1_MessageItem0.StartValue = 1;
			this.Group1.Messages.Add(this.Group1_MessageItem0);
			this.Group1.Name = "Group1";
			this.Groups.Add(this.Group1);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(TextLibrary));
			this.m_Group1_MessageItem0.Message = resources.GetText("TextLibrary.Group1_MessageItem0.Message", "ASD");
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
